"""Alembic environment.

The database URL always comes from application settings so migrations can never
target a different database than the app.
"""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.config import settings  # noqa: E402
from app.models import Base  # noqa: E402  (registers every mapper)

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _compare_server_default(
    context, inspected_column, metadata_column, inspected_default, metadata_default, rendered
):
    """Ignore drift on uuid primary-key defaults.

    `gen_random_uuid()` is Postgres-only, so it is applied by a migration and
    deliberately absent from the models. Without this hook every autogenerated
    revision proposes `ALTER COLUMN id DROP DEFAULT` for all of them — which
    silently strips the defaults that make trigger and client-side inserts
    valid. Returning False means "no change".
    """
    if inspected_column is not None and inspected_column.name == "id":
        if inspected_default and "gen_random_uuid" in str(inspected_default):
            return False
    return None  # fall back to Alembic's own comparison


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=_compare_server_default,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=_compare_server_default,
            # SQLite cannot ALTER most things in place; batch mode rewrites the
            # table instead so the same migration chain works on both backends.
            render_as_batch=connection.dialect.name == "sqlite",
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
