"""sheet provenance, problem hints and video links

Revision ID: 2392beffef44
Revises: b1f4c2d9e701
Create Date: 2026-08-17 17:04:07.449912
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # custom column types referenced below


revision: str = '2392beffef44'
down_revision: str | None = 'b1f4c2d9e701'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Only the three new columns. Autogenerate also proposed dropping the UUID
    # primary-key defaults, because `gen_random_uuid()` is applied in the
    # Postgres-only migration and deliberately absent from the models — those
    # proposals are rejected here, since honouring them would strip the very
    # defaults that make direct/trigger inserts valid.
    op.add_column("sheets", sa.Column("source_metadata", app.db.types.JSONType(), nullable=True))
    op.add_column("problems", sa.Column("hints", app.db.types.JSONType(), nullable=True))
    op.add_column("problems", sa.Column("video_links", app.db.types.JSONType(), nullable=True))

    # Re-assert the Postgres UUID defaults. An earlier revision of THIS
    # migration was autogenerated with `ALTER COLUMN id DROP DEFAULT` for every
    # uuid primary key and stripped them; this restores any database that ran
    # it. Idempotent, so fresh installs are unaffected.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            DO $$
            DECLARE target record;
            BEGIN
                FOR target IN
                    SELECT c.table_name FROM information_schema.columns c
                    WHERE c.table_schema = 'public' AND c.column_name = 'id'
                      AND c.data_type = 'uuid' AND c.column_default IS NULL
                LOOP
                    EXECUTE format(
                        'ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT gen_random_uuid()',
                        target.table_name);
                END LOOP;
            END $$
            """
        )


def downgrade() -> None:
    op.drop_column("problems", "video_links")
    op.drop_column("problems", "hints")
    op.drop_column("sheets", "source_metadata")
