"""initial schema

Revision ID: 3ee3a8277a90
Revises: 
Create Date: 2026-08-16 23:40:58.773801
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # custom column types referenced below


revision: str = '3ee3a8277a90'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('criteria', app.db.types.JSONType(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('code', name=op.f('uq_achievements_code'))
    )
    op.create_table('contests',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('start_time', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('contest_type', sa.String(length=32), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contests')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_contests_platform_external')
    )
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contests_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_contests_start_time'), ['start_time'], unique=False)

    op.create_table('problems',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_source', sa.String(length=32), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=True),
    sa.Column('solved_count', sa.Integer(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('problem_index', sa.String(length=8), nullable=True),
    sa.Column('tags', app.db.types.JSONType(), nullable=True),
    sa.Column('extra', app.db.types.JSONType(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('metadata_complete', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_problems_platform_external_id')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_contest_id'), ['contest_id'], unique=False)
        batch_op.create_index('ix_problems_difficulty', ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_problems_rating', ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_slug'), ['slug'], unique=False)

    op.create_table('profiles',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_email'), ['email'], unique=False)

    op.create_table('sheets',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheets')),
    sa.UniqueConstraint('slug', name=op.f('uq_sheets_slug'))
    )
    op.create_table('topics',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', app.db.types.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_topics_slug'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_path'), ['path'], unique=False)

    op.create_table('activity_days',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('activity_date', app.db.types.DateType(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('minutes_spent', sa.Integer(), nullable=False),
    sa.Column('submissions', sa.Integer(), nullable=False),
    sa.Column('contests', sa.Integer(), nullable=False),
    sa.Column('upsolves', sa.Integer(), nullable=False),
    sa.Column('reviews_completed', sa.Integer(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('topics_touched', app.db.types.JSONType(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_activity_days_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_days')),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_activity_days_user_date')
    )
    with op.batch_alter_table('activity_days', schema=None) as batch_op:
        batch_op.create_index('ix_activity_days_user_date', ['user_id', 'activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_days_user_id'), ['user_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_ai_conversations_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('ai_insights',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_output', app.db.types.JSONType(), nullable=True),
    sa.Column('context_snapshot', app.db.types.JSONType(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('data_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('subject_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_ai_insights_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insights'))
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index('ix_ai_insights_snapshot', ['user_id', 'type', 'data_snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_ai_insights_user_type_generated', ['user_id', 'type', 'generated_at'], unique=False)

    op.create_table('ai_usage',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_ai_usage_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index('ix_ai_usage_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('collections',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_collections_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('user_id', 'slug', name='uq_collections_user_slug')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    op.create_table('contest_participations',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('contest_id', app.db.types.GUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rating_before', sa.Integer(), nullable=True),
    sa.Column('rating_after', sa.Integer(), nullable=True),
    sa.Column('rating_change', sa.Integer(), nullable=True),
    sa.Column('problems_solved_live', sa.Integer(), nullable=False),
    sa.Column('problems_upsolved', sa.Integer(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], name=op.f('fk_contest_participations_contest_id_contests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_contest_participations_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_participations')),
    sa.UniqueConstraint('user_id', 'contest_id', 'is_virtual', name='uq_contest_participations_user_contest')
    )
    with op.batch_alter_table('contest_participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_participations_contest_id'), ['contest_id'], unique=False)
        batch_op.create_index('ix_contest_participations_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_participations_user_id'), ['user_id'], unique=False)

    op.create_table('contest_problem_results',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('contest_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('solved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('time_from_start_seconds', sa.Integer(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], name=op.f('fk_contest_problem_results_contest_id_contests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_contest_problem_results_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_contest_problem_results_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_problem_results')),
    sa.UniqueConstraint('user_id', 'contest_id', 'problem_id', name='uq_contest_problem_results_unique')
    )
    with op.batch_alter_table('contest_problem_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_problem_results_contest_id'), ['contest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_problem_results_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_problem_results_user_id'), ['user_id'], unique=False)

    op.create_table('contest_problems',
    sa.Column('contest_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('index', sa.String(length=8), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], name=op.f('fk_contest_problems_contest_id_contests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_contest_problems_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_problems')),
    sa.UniqueConstraint('contest_id', 'problem_id', name='uq_contest_problems_contest_problem')
    )
    with op.batch_alter_table('contest_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_problems_contest_id'), ['contest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_problems_problem_id'), ['problem_id'], unique=False)

    op.create_table('daily_goals',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('goal_date', app.db.types.DateType(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_daily_goals_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_goals')),
    sa.UniqueConstraint('user_id', 'goal_date', name='uq_daily_goals_user_date')
    )
    with op.batch_alter_table('daily_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_goals_user_id'), ['user_id'], unique=False)

    op.create_table('daily_missions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('mission_date', app.db.types.DateType(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('params', app.db.types.JSONType(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_daily_missions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_missions')),
    sa.UniqueConstraint('user_id', 'mission_date', 'code', name='uq_daily_missions_user_date_code')
    )
    with op.batch_alter_table('daily_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_missions_user_id'), ['user_id'], unique=False)

    op.create_table('patterns',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic_id', app.db.types.GUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_patterns_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patterns')),
    sa.UniqueConstraint('slug', name=op.f('uq_patterns_slug'))
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_topic_id'), ['topic_id'], unique=False)

    op.create_table('platform_accounts',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('sync_cursor', app.db.types.JSONType(), nullable=True),
    sa.Column('current_rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_platform_accounts_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_accounts')),
    sa.UniqueConstraint('user_id', 'platform', name='uq_platform_accounts_user_platform')
    )
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('problem_notes',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_notes_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_problem_notes_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_notes'))
    )
    with op.batch_alter_table('problem_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_notes_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_notes_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_problem_notes_user_problem', ['user_id', 'problem_id'], unique=False)

    op.create_table('problem_topics',
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('topic_id', app.db.types.GUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_topics_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_problem_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'topic_id', name=op.f('pk_problem_topics'))
    )
    op.create_table('recommendations',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('evidence', app.db.types.JSONType(), nullable=True),
    sa.Column('generated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('dismissed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('accepted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_recommendations_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_recommendations_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'problem_id', 'batch_id', name='uq_recommendations_user_problem_batch')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index('ix_recommendations_user_generated', ['user_id', 'generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('resources',
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', app.db.types.JSONType(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_resources_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_resources_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('problem_id', 'url', name='uq_resources_problem_url')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('scheduled_for', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('evidence', app.db.types.JSONType(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_reviews_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_reviews_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reviews_user_scheduled', ['user_id', 'scheduled_for', 'completed_at'], unique=False)

    op.create_table('sheet_sections',
    sa.Column('sheet_id', app.db.types.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rating_bucket', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('topic_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_sheet_sections_sheet_id_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_sheet_sections_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_sections')),
    sa.UniqueConstraint('sheet_id', 'slug', name='uq_sheet_sections_sheet_slug')
    )
    with op.batch_alter_table('sheet_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheet_sections_rating_bucket'), ['rating_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheet_sections_sheet_id'), ['sheet_id'], unique=False)

    op.create_table('solving_sessions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('solution_source', sa.String(length=16), nullable=False),
    sa.Column('difficulty_perception', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_solving_sessions_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_solving_sessions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solving_sessions'))
    )
    with op.batch_alter_table('solving_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solving_sessions_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index('ix_solving_sessions_user_finished', ['user_id', 'finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_solving_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('streak_freeze_transactions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('xp_cost', sa.Integer(), nullable=False),
    sa.Column('applies_to_date', app.db.types.DateType(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_streak_freeze_transactions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streak_freeze_transactions')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_streak_freeze_transactions_user_dedupe')
    )
    with op.batch_alter_table('streak_freeze_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streak_freeze_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('submissions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_submission_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_contest_id', sa.String(length=64), nullable=True),
    sa.Column('during_contest', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_submissions_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_submissions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('user_id', 'platform', 'external_submission_id', name='uq_submissions_user_platform_external')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_is_accepted'), ['is_accepted'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_submissions_user_problem', ['user_id', 'problem_id'], unique=False)
        batch_op.create_index('ix_submissions_user_submitted', ['user_id', 'submitted_at'], unique=False)

    op.create_table('sync_runs',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submissions_fetched', sa.Integer(), nullable=False),
    sa.Column('submissions_new', sa.Integer(), nullable=False),
    sa.Column('problems_created', sa.Integer(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', app.db.types.JSONType(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_sync_runs_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sync_runs_user_platform', ['user_id', 'platform', 'started_at'], unique=False)

    op.create_table('trusted_channels',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_trusted_channels_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_channels')),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_trusted_channels_user_channel')
    )
    with op.batch_alter_table('trusted_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trusted_channels_user_id'), ['user_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('achievement_id', app.db.types.GUID(), nullable=False),
    sa.Column('unlocked_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_user_achievements_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievements_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('user_problems',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_solved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_solved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_attempted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('best_solution_source', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_due_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_user_problems_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_user_problems_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_problems')),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problems_user_problem')
    )
    with op.batch_alter_table('user_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_problems_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index('ix_user_problems_review_due', ['user_id', 'review_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_problems_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_problems_user_status', ['user_id', 'status'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('weekly_goal', sa.Integer(), server_default=sa.text('(14)'), nullable=False),
    sa.Column('max_freezes', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('freeze_cost_xp', sa.Integer(), server_default=sa.text('(500)'), nullable=False),
    sa.Column('auto_apply_freeze', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('xp_rules_override', app.db.types.JSONType(), nullable=True),
    sa.Column('level_config_override', app.db.types.JSONType(), nullable=True),
    sa.Column('streak_qualifying_activities', app.db.types.JSONType(), nullable=True),
    sa.Column('ai_daily_insights', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('ai_weekly_reviews', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('ai_contest_analysis', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('ai_recommendations', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('ai_coach', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('ai_daily_request_budget', sa.Integer(), server_default=sa.text('(50)'), nullable=False),
    sa.Column('ai_model_override', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_user_settings_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('user_stats',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_active_date', app.db.types.DateType(), nullable=True),
    sa.Column('available_freezes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('problems_solved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('independent_solves', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_recomputed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_user_stats_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_stats'))
    )
    op.create_table('weekly_goals',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('week_start', app.db.types.DateType(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('params', app.db.types.JSONType(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_weekly_goals_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_goals')),
    sa.UniqueConstraint('user_id', 'week_start', 'kind', name='uq_weekly_goals_user_week_kind')
    )
    with op.batch_alter_table('weekly_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_goals_user_id'), ['user_id'], unique=False)

    op.create_table('xp_transactions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=True),
    sa.Column('activity_date', app.db.types.DateType(), nullable=False),
    sa.Column('awarded_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_xp_transactions_problem_id_problems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_xp_transactions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_transactions')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_xp_transactions_user_dedupe')
    )
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_xp_transactions_user_date', ['user_id', 'activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('conversation_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', app.db.types.JSONType(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_ai_messages_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index('ix_ai_messages_conversation', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_user_id'), ['user_id'], unique=False)

    op.create_table('collection_problems',
    sa.Column('collection_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_problems_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_collection_problems_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_problems')),
    sa.UniqueConstraint('collection_id', 'problem_id', name='uq_collection_problems_collection_problem')
    )
    with op.batch_alter_table('collection_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_problems_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_problems_problem_id'), ['problem_id'], unique=False)

    op.create_table('mistakes',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('session_id', app.db.types.GUID(), nullable=True),
    sa.Column('mistake_type', sa.String(length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_mistakes_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['solving_sessions.id'], name=op.f('fk_mistakes_session_id_solving_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_mistakes_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistakes'))
    )
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mistakes_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_mistakes_user_type', ['user_id', 'mistake_type'], unique=False)

    op.create_table('problem_patterns',
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('pattern_id', app.db.types.GUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_problem_patterns_pattern_id_patterns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_patterns_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'pattern_id', name=op.f('pk_problem_patterns'))
    )
    op.create_table('sheet_problems',
    sa.Column('sheet_id', app.db.types.GUID(), nullable=False),
    sa.Column('section_id', app.db.types.GUID(), nullable=True),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_sheet_problems_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sheet_sections.id'], name=op.f('fk_sheet_problems_section_id_sheet_sections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_sheet_problems_sheet_id_sheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_problems')),
    sa.UniqueConstraint('sheet_id', 'problem_id', name='uq_sheet_problems_sheet_problem')
    )
    with op.batch_alter_table('sheet_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheet_problems_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheet_problems_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheet_problems_sheet_id'), ['sheet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheet_problems_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_sheet_problems_section_id'))
        batch_op.drop_index(batch_op.f('ix_sheet_problems_problem_id'))

    op.drop_table('sheet_problems')
    op.drop_table('problem_patterns')
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index('ix_mistakes_user_type')
        batch_op.drop_index(batch_op.f('ix_mistakes_user_id'))
        batch_op.drop_index(batch_op.f('ix_mistakes_problem_id'))

    op.drop_table('mistakes')
    with op.batch_alter_table('collection_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_problems_problem_id'))
        batch_op.drop_index(batch_op.f('ix_collection_problems_collection_id'))

    op.drop_table('collection_problems')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_user_id'))
        batch_op.drop_index('ix_ai_messages_conversation')

    op.drop_table('ai_messages')
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_transactions_user_id'))
        batch_op.drop_index('ix_xp_transactions_user_date')

    op.drop_table('xp_transactions')
    with op.batch_alter_table('weekly_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_goals_user_id'))

    op.drop_table('weekly_goals')
    op.drop_table('user_stats')
    op.drop_table('user_settings')
    with op.batch_alter_table('user_problems', schema=None) as batch_op:
        batch_op.drop_index('ix_user_problems_user_status')
        batch_op.drop_index(batch_op.f('ix_user_problems_user_id'))
        batch_op.drop_index('ix_user_problems_review_due')
        batch_op.drop_index(batch_op.f('ix_user_problems_problem_id'))

    op.drop_table('user_problems')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievements_achievement_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('trusted_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_channels_user_id'))

    op.drop_table('trusted_channels')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_runs_user_platform')
        batch_op.drop_index(batch_op.f('ix_sync_runs_user_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_user_submitted')
        batch_op.drop_index('ix_submissions_user_problem')
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_problem_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_is_accepted'))

    op.drop_table('submissions')
    with op.batch_alter_table('streak_freeze_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streak_freeze_transactions_user_id'))

    op.drop_table('streak_freeze_transactions')
    with op.batch_alter_table('solving_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solving_sessions_user_id'))
        batch_op.drop_index('ix_solving_sessions_user_finished')
        batch_op.drop_index(batch_op.f('ix_solving_sessions_problem_id'))

    op.drop_table('solving_sessions')
    with op.batch_alter_table('sheet_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheet_sections_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_sheet_sections_rating_bucket'))

    op.drop_table('sheet_sections')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_user_scheduled')
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_problem_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_user_id'))
        batch_op.drop_index(batch_op.f('ix_resources_problem_id'))
        batch_op.drop_index(batch_op.f('ix_resources_channel_id'))

    op.drop_table('resources')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index('ix_recommendations_user_generated')
        batch_op.drop_index(batch_op.f('ix_recommendations_problem_id'))

    op.drop_table('recommendations')
    op.drop_table('problem_topics')
    with op.batch_alter_table('problem_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_problem_notes_user_problem')
        batch_op.drop_index(batch_op.f('ix_problem_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_problem_notes_problem_id'))

    op.drop_table('problem_notes')
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_accounts_user_id'))

    op.drop_table('platform_accounts')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_topic_id'))

    op.drop_table('patterns')
    with op.batch_alter_table('daily_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_missions_user_id'))

    op.drop_table('daily_missions')
    with op.batch_alter_table('daily_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_goals_user_id'))

    op.drop_table('daily_goals')
    with op.batch_alter_table('contest_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_problems_problem_id'))
        batch_op.drop_index(batch_op.f('ix_contest_problems_contest_id'))

    op.drop_table('contest_problems')
    with op.batch_alter_table('contest_problem_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_problem_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_contest_problem_results_problem_id'))
        batch_op.drop_index(batch_op.f('ix_contest_problem_results_contest_id'))

    op.drop_table('contest_problem_results')
    with op.batch_alter_table('contest_participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_participations_user_id'))
        batch_op.drop_index('ix_contest_participations_user')
        batch_op.drop_index(batch_op.f('ix_contest_participations_contest_id'))

    op.drop_table('contest_participations')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))

    op.drop_table('collections')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index('ix_ai_usage_user_created')

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_insights_user_type_generated')
        batch_op.drop_index(batch_op.f('ix_ai_insights_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_subject_id'))
        batch_op.drop_index('ix_ai_insights_snapshot')

    op.drop_table('ai_insights')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('activity_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_days_user_id'))
        batch_op.drop_index('ix_activity_days_user_date')

    op.drop_table('activity_days')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_path'))
        batch_op.drop_index(batch_op.f('ix_topics_parent_id'))

    op.drop_table('topics')
    op.drop_table('sheets')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_email'))

    op.drop_table('profiles')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_slug'))
        batch_op.drop_index('ix_problems_rating')
        batch_op.drop_index(batch_op.f('ix_problems_platform'))
        batch_op.drop_index('ix_problems_difficulty')
        batch_op.drop_index(batch_op.f('ix_problems_contest_id'))

    op.drop_table('problems')
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contests_start_time'))
        batch_op.drop_index(batch_op.f('ix_contests_platform'))

    op.drop_table('contests')
    op.drop_table('achievements')
    # ### end Alembic commands ###
