"""icpc mode

Revision ID: 7dbfc979dac3
Revises: 2392beffef44
Create Date: 2026-08-17 17:10:50.906121
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # custom column types referenced below


revision: str = '7dbfc979dac3'
down_revision: str | None = '2392beffef44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icpc_settings',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('target_date', app.db.types.DateType(), nullable=True),
    sa.Column('team_name', sa.String(length=128), nullable=True),
    sa.Column('weekly_practice_days', sa.Integer(), nullable=False),
    sa.Column('focus_topics', app.db.types.JSONType(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_icpc_settings_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_icpc_settings'))
    )
    op.create_table('icpc_topic_progress',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('topic_key', sa.String(length=128), nullable=False),
    sa.Column('studied', sa.Boolean(), nullable=False),
    sa.Column('template_reviewed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('last_practiced_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_icpc_topic_progress_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icpc_topic_progress')),
    sa.UniqueConstraint('user_id', 'topic_key', name='uq_icpc_topic_progress_user_topic')
    )
    op.create_index(op.f('ix_icpc_topic_progress_user_id'), 'icpc_topic_progress', ['user_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('target_problems', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('focus_topic', sa.String(length=128), nullable=True),
    sa.Column('min_rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('problem_ids', app.db.types.JSONType(), nullable=True),
    sa.Column('summary', app.db.types.JSONType(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_practice_sessions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sessions'))
    )
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_index('ix_practice_sessions_user_started', 'practice_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('readiness_snapshots',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('taken_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('components', app.db.types.JSONType(), nullable=False),
    sa.Column('has_sufficient_data', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_readiness_snapshots_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_snapshots'))
    )
    op.create_index(op.f('ix_readiness_snapshots_user_id'), 'readiness_snapshots', ['user_id'], unique=False)
    op.create_index('ix_readiness_snapshots_user_taken', 'readiness_snapshots', ['user_id', 'taken_at'], unique=False)
    op.create_table('template_reviews',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('template_slug', sa.String(length=64), nullable=False),
    sa.Column('reviewed_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('from_memory', sa.Boolean(), nullable=False),
    sa.Column('seconds_taken', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_template_reviews_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_reviews'))
    )
    op.create_index(op.f('ix_template_reviews_user_id'), 'template_reviews', ['user_id'], unique=False)
    op.create_index('ix_template_reviews_user_slug', 'template_reviews', ['user_id', 'template_slug'], unique=False)
    op.create_table('virtual_contests',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('penalty_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_virtual_contests_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_virtual_contests'))
    )
    op.create_index(op.f('ix_virtual_contests_user_id'), 'virtual_contests', ['user_id'], unique=False)
    op.create_index('ix_virtual_contests_user_started', 'virtual_contests', ['user_id', 'started_at'], unique=False)
    op.create_table('hint_reveals',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('hint_index', sa.Integer(), nullable=False),
    sa.Column('revealed_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('session_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_hint_reveals_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], name=op.f('fk_hint_reveals_session_id_practice_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_hint_reveals_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hint_reveals')),
    sa.UniqueConstraint('user_id', 'problem_id', 'hint_index', name='uq_hint_reveals_user_problem_index')
    )
    op.create_index(op.f('ix_hint_reveals_problem_id'), 'hint_reveals', ['problem_id'], unique=False)
    op.create_index(op.f('ix_hint_reveals_user_id'), 'hint_reveals', ['user_id'], unique=False)
    op.create_table('virtual_contest_problems',
    sa.Column('contest_id', app.db.types.GUID(), nullable=False),
    sa.Column('problem_id', app.db.types.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wrong_attempts', sa.Integer(), nullable=False),
    sa.Column('solved_at_minute', sa.Integer(), nullable=True),
    sa.Column('upsolved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['virtual_contests.id'], name=op.f('fk_virtual_contest_problems_contest_id_virtual_contests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_virtual_contest_problems_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_virtual_contest_problems')),
    sa.UniqueConstraint('contest_id', 'problem_id', name='uq_virtual_contest_problems_contest_problem')
    )
    op.create_index(op.f('ix_virtual_contest_problems_contest_id'), 'virtual_contest_problems', ['contest_id'], unique=False)
    op.create_index(op.f('ix_virtual_contest_problems_problem_id'), 'virtual_contest_problems', ['problem_id'], unique=False)
    # NOTE: autogenerate proposed `server_default=None` on every uuid `id`
    # here. Those were removed by hand and are now suppressed permanently by
    # `_compare_server_default` in alembic/env.py — honouring them strips the
    # Postgres-only gen_random_uuid() defaults that trigger and client-side
    # inserts depend on.
    _reassert_uuid_defaults()
    # ### end Alembic commands ###


def _reassert_uuid_defaults() -> None:
    """Idempotently (re)apply gen_random_uuid() to every uuid primary key,
    including the tables this revision creates."""
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        """
        DO $$
        DECLARE target record;
        BEGIN
            FOR target IN
                SELECT c.table_name FROM information_schema.columns c
                WHERE c.table_schema = 'public' AND c.column_name = 'id'
                  AND c.data_type = 'uuid' AND c.column_default IS NULL
            LOOP
                EXECUTE format(
                    'ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT gen_random_uuid()',
                    target.table_name);
            END LOOP;
        END $$
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_contest_problems_problem_id'), table_name='virtual_contest_problems')
    op.drop_index(op.f('ix_virtual_contest_problems_contest_id'), table_name='virtual_contest_problems')
    op.drop_table('virtual_contest_problems')
    op.drop_index(op.f('ix_hint_reveals_user_id'), table_name='hint_reveals')
    op.drop_index(op.f('ix_hint_reveals_problem_id'), table_name='hint_reveals')
    op.drop_table('hint_reveals')
    op.drop_index('ix_virtual_contests_user_started', table_name='virtual_contests')
    op.drop_index(op.f('ix_virtual_contests_user_id'), table_name='virtual_contests')
    op.drop_table('virtual_contests')
    op.drop_index('ix_template_reviews_user_slug', table_name='template_reviews')
    op.drop_index(op.f('ix_template_reviews_user_id'), table_name='template_reviews')
    op.drop_table('template_reviews')
    op.drop_index('ix_readiness_snapshots_user_taken', table_name='readiness_snapshots')
    op.drop_index(op.f('ix_readiness_snapshots_user_id'), table_name='readiness_snapshots')
    op.drop_table('readiness_snapshots')
    op.drop_index('ix_practice_sessions_user_started', table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_icpc_topic_progress_user_id'), table_name='icpc_topic_progress')
    op.drop_table('icpc_topic_progress')
    op.drop_table('icpc_settings')
    # ### end Alembic commands ###
